//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int CodigoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string CiudadCliente { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    }
}
